[package]
name = "inner"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
bench = false

[dependencies]
chrono = "0.4.31"
uniffi = "=0.25.0"
