[package]
name = "outer"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
bench = false

[dependencies]
inner = { path = "../inner" }
chrono = "0.4.31"
uniffi = "=0.25.0"
